[workspace]
resolver = "2"
members  = [
    "mass_events_worker",
    "mass_events_utils",
    "mass_events_scheduler",
    "mass_events_process_runner_models",
    "mass_events_process_runner_client",
    "mass_events_process_runner",
]